spring:
  application:
    name: mell-third-party
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
server:
  port: 30000
minio:
  endpoint: http://192.168.32.151:9000 #MinIO服务所在地址
  bucketName: public #存储桶名称
  accessKey: 14Fbz08745juBznb #访问的key
  secretKey: ZSmZPENqXhvJFKStgHkJp9DV5IUaAc7y #访问的秘钥






