spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 5201314
    url: jdbc:mysql://192.168.32.151:3306/mell_ums
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: mell-member
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000